# Generated by Django 4.0.1 on 2022-03-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_student_user_is_cit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_cit',
            new_name='is_acc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sv',
        ),
        migrations.AddField(
            model_name='user',
            name='is_hm',
            field=models.BooleanField(default=False, max_length=10),
        ),
    ]
