# Generated by Django 4.0.1 on 2022-03-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Middle_Name',
            field=models.CharField(default='Job', max_length=20),
        ),
    ]
