# Generated by Django 4.0.1 on 2022-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0002_student_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Last_Name',
            field=models.CharField(default='Job', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='ParentAddress',
            field=models.CharField(default='Job', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Parent_Occupation',
            field=models.CharField(default='Job', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_Education',
            field=models.CharField(default='Job', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='Job', max_length=20),
        ),
    ]
