# Generated by Django 4.0.1 on 2022-03-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0003_student_last_name_student_parentaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Local',
            field=models.CharField(default='Job', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Parent_Name',
            field=models.CharField(default='Job', max_length=20),
        ),
    ]
