# Generated by Django 4.0.1 on 2022-03-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0004_student_local_student_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Birthd_Certificate',
            field=models.CharField(default='Job', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Birthd_Date',
            field=models.CharField(default='Job', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Description',
            field=models.TextField(default='Job', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Nida_Number',
            field=models.CharField(default='Job', max_length=20),
        ),
    ]
