# Generated by Django 4.0.1 on 2022-03-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0005_student_birthd_certificate_student_birthd_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payments', models.CharField(choices=[('Payments', (('1st quarter', '1st qurter'), ('2nd quarter', '2st qurter'), ('3rd quarter', '3rd qurter'), ('4th quarter', '4th qurter')))], default='available', max_length=32)),
                ('Cno', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountant.student')),
            ],
        ),
    ]
