# Generated by Django 4.0.1 on 2022-03-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0006_studentfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StudentFoodFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=2000)),
                ('amount', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountant.student')),
            ],
        ),
    ]
