# Generated by Django 4.0.1 on 2022-03-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accountant', '0008_studentuniformfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransportFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datepaid', models.DateField(auto_created=True, auto_now_add=True)),
                ('month', models.CharField(choices=[('Payments', (('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'Appril')))], default='January', max_length=50)),
                ('Cno', models.IntegerField()),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountant.student')),
            ],
        ),
    ]
