# Generated by Django 4.0.1 on 2022-04-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Headmaster', '0001_initial'),
        ('Accountant', '0010_studentfee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Headmaster.student'),
        ),
        migrations.AlterField(
            model_name='studentfoodfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Headmaster.student'),
        ),
        migrations.AlterField(
            model_name='studentfoodfee',
            name='totalAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studenttransportfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Headmaster.student'),
        ),
        migrations.AlterField(
            model_name='studentuniformfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Headmaster.student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
