# Generated by Django 4.0.1 on 2022-04-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='Job', max_length=20)),
                ('Middle_Name', models.CharField(default='Job', max_length=20)),
                ('Last_Name', models.CharField(default='Job', max_length=20)),
                ('Parent_Name', models.CharField(default='Job', max_length=20)),
                ('Parent_Occupation', models.CharField(default='Job', max_length=20)),
                ('parent_Education', models.CharField(default='Job', max_length=20)),
                ('ParentAddress', models.CharField(default='Job', max_length=20)),
                ('Birthd_Date', models.CharField(default='Job', max_length=20)),
                ('Local', models.CharField(default='Job', max_length=20)),
                ('Description', models.TextField(default='Job', max_length=20)),
                ('Nida_Number', models.CharField(default='Job', max_length=20)),
                ('Birthd_Certificate', models.CharField(default='Job', max_length=20)),
                ('phone', models.CharField(default='Job', max_length=20)),
            ],
        ),
    ]
